### ISSUE TITLE
Error in workflow 'com.chrisbro.bear'

### ISSUE THREAD

**Issue by heyhler** [chrisbro/alfred-bear#17] opened 2018-09-18 00:43 UTC
Probably something on the user end, but I'm getting this error with the "bs" command. Is there a way for me to reassociate whatever needs reassociating?
<img width="600" alt="screen shot 2018-09-17 at 7 43 19 pm" src="https://user-images.githubusercontent.com/34072119/45657912-f6f48d80-bab1-11e8-8818-02151e97be17.png">

**Comment by fremontmj** [comment] 2018-09-18 20:44
just update Bear, and I'm getting it too

**Comment by chrisbro** [comment] 2018-09-18 22:32
Crap, can't reproduce on 1.6.1 (6731) and Alfred 3.7.

Do you see anything at either of these locations? Let's see if they moved the database file again.

> ls ~/Library/Containers/net.shinyfrog.bear/Data/Library/Application\ Support/net.shinyfrog.bear/database.sqlite
> ls ~/Library/Containers/net.shinyfrog.bear/Data/Documents/Application\ Data/database.sqlite

**Comment by tjurczyk** [comment] 2018-09-18 22:37
@chrisbro just came here with the same problem and to answer your questions, sqlites are not there:

```
(python3) george@Tomaszs-MacBook-Pro:~ $ ls ~/Library/Containers/net.shinyfrog.bear/Data/Documents/
iChats
```

```
(python3) george@Tomaszs-MacBook-Pro:~ $ ls ~/Library/Containers/net.shinyfrog.bear/Data/Library/Application\ Support/net.shinyfrog.bear/
Thumbs
```

**Comment by juung** [comment] 2018-09-19 04:02
Me too. Workflow doesn't work after I updated Bear App.

**Comment by dsumin** [comment] 2018-09-19 09:14
Database was moved to:
~/Library/Group\ Containers/9K33E3U3T4.net.shinyfrog.bear/Application\ Data/database.sqlite

**Comment by chrisbro** [comment] 2018-09-19 12:46
I was able to repro on my work Macbook (no clue why the personal one still seems fine). And the location matches what @dsumin found.

I'll try to get a patch out tonight! 

In the meantime, I don't know what this new location is (specifically the "9K33E3U3T4" portion) and how stable it's going to be. Anyone know if that's going to be changing with every update? Doesn't seem that way, glancing at created at dates on some other apps in .../Group Containers/ .

**Comment by dsumin** [comment] 2018-09-19 13:43
> I don't know what this new location is (specifically the "9K33E3U3T4" portion) and how stable it's going to be.

This is an application-specific UID, so I hope this won't change for some time.

**Comment by chrisbro** [comment] 2018-09-19 23:12
Ah, I see why it works on my personal machine - for some reason the old sqlite database in the old location is there. It's not getting synced to, though. I'll have the patch look for the new location before the old one.

**Comment by chrisbro** [comment] 2018-09-19 23:35
Fixed! Y'all give it a shot by grabbing the workflow [here](https://github.com/chrisbro/alfred-bear/releases/tag/0.3.2).

**Comment by chrisbro** [comment] 2018-09-19 23:36
Closing issue out.

**Closed by chrisbro** 2018-09-19 23:36 UTC

**Comment by heyhler** [comment] 2018-09-20 00:17
> Fixed! Y'all give it a shot by grabbing the workflow [here](https://github.com/chrisbro/alfred-bear/releases/tag/0.3.2).

Working properly now! Thanks a ton!

**Comment by dsumin** [comment] 2018-09-20 09:20
Thank you for getting this fixed quick! That resolves the issue!

**Comment by brandonpittman** [comment] 2018-11-15 13:55
Funny, I'm getting the same damn error on 0.3.3
