### ISSUE TITLE
Is 0.3.4 only compatible with Alfred 4?

### ISSUE THREAD

**Issue by ejolly** [chrisbro/alfred-bear#25] opened 2019-09-09 19:14 UTC
I'm getting a workflow incompatible issue when using this new release with Alfred 3.8.2 [963] which appears to be the latest Alfred v3 release.

**Comment by chrisbro** [comment] 2019-09-09 19:19
@ejolly Not by design - though there were some changes in the info.plist file when I saved it that I didn't recognize, so I wonder if just saving the new one from my version of Alfred jacked it up. Let me see if I can figure that out.

**Comment by chrisbro** [comment] 2019-09-09 19:47
@ejolly Give [0.3.5](https://github.com/chrisbro/alfred-bear/releases/tag/0.3.5) a shot. Sorry about that, should've known better but it's been awhile since the last release and I neglected to test in Alfred 3.

**Comment by ejolly** [comment] 2019-09-09 19:52
No worries. 0.3.5 works like a charm! Thanks for the fast fix, and of course for the great workflow!

**Comment by chrisbro** [comment] 2019-09-09 19:53
Cool! Closing - fixed in [0.3.5](https://github.com/chrisbro/alfred-bear/releases/tag/0.3.5).

**Closed by chrisbro** 2019-09-09 19:53 UTC
Labels: bug
